        1.) Se considera un vector, continand nnumere naturale cuprinse
intre 1 si 600000. Sa se alcatuiasca un program care sa ordoneze crescator
doar numerele pare din vector, fara insa a afecta pozitiile pe care sunt
numerele inpare
ex:          n=7
   vectorul: 1   40   32   44   3    8   17
   rez:      1    8   32   40   3    44  17

        2.) In fisierul text INPUT.TXT se gasesc doua propozitii scrise
pe cate o linie. Propozitiile contin cuvinte formate doar din literele
alfabetului englez. Orice alt caracter este considerat separator. Scrieti
un program care sa determine:
a.)Numarul de cuvinte din fiecare prop.
b.)Considerand ultimul cuvant din fiecare prop. scrieti o functie care
verifica daca aceste doua cuvinte sunt anagrame(contin acelasi litere)
Raspunsurile intr-un fisier de text
ex:
INPUT.TXT
A reusit... o ia ca atare
Da, cel mai mult a studiat erata
OUTPUT.TXT
6
7
DA

        3.)Se considera o matrice A de dimensiune m*n.Sa se reaseze elementele
din matrice a.i. ele sa apara in ordine crescatoare atat pe linii cat si pe
coloane.Matricea A se gaseste in fisierul de intrare "INPUT.TXT"fiecare linie
a matricii pe cate o linie din fisier (Valoarea lui n si m nu este specificata)
Matricea obtinuta se va afisa la fel in fisierul "OUTPUT.TXT".
